### ISSUE TITLE
Add usage guidelines and/or support for exporting keys to plaintext

### ISSUE THREAD

**Issue by rchekaluk** [github/ssh_data#17]
Seeking guidance on how to export parsed or generated keys to plaintext in formats analogous to ssh-keygen:
* [dsa.plaintext.pem](https://github.com/github/ssh_data/blob/master/spec/fixtures/dsa.plaintext.pem)
* [ecdsa.plaintext.pem](https://github.com/github/ssh_data/blob/master/spec/fixtures/ecdsa.plaintext.pem)
* [ed25519_ca](https://github.com/github/ssh_data/blob/master/spec/fixtures/ed25519_ca)
* [rsa.plaintext.pem](https://github.com/github/ssh_data/blob/master/spec/fixtures/rsa.plaintext.pem)
* [dsa_ca.pub](https://github.com/github/ssh_data/blob/master/spec/fixtures/dsa_ca.pub)
* [ecdsa_ca.pub](https://github.com/github/ssh_data/blob/master/spec/fixtures/ecdsa_ca.pub)
* [ed25519_ca.pub](https://github.com/github/ssh_data/blob/master/spec/fixtures/ed25519_ca.pub)
* [rsa_ca.pub](https://github.com/github/ssh_data/blob/master/spec/fixtures/rsa_ca.pub)

**Comment by vcsjones** [comment]
@excid3 

Assuming you have a `SSHData::PublicKey` instance, like:

```ruby
key = SSHData::PublicKey.parse_openssh(File.read('spec/fixtures/ed25519_ca.pub'))
```

It should be something like:

```ruby
require 'base64'
openssh_key = key.algo + ' ' + Base64.strict_encode64(key.rfc4253)
```

**Comment by vcsjones** [comment]
Assuming this is what folks I looking for, I can take a moment to add this to some docs.

**Comment by excid3** [comment]
@vcsjones Awesome! What about for writing a private key?

**Comment by vcsjones** [comment]
Private key is a little more complicated, we don't have a good abstraction to go from a private key to an OpenSSH key. We do have the opposite of importing, the keys, just not exporting them. Let me see what this would take and what improvements could be made.

**Comment by vcsjones** [comment]
At this point, we don't have any plans to expand the scope and purpose of private key functionality in this gem which would be needed to create an OpenSSH key from a private key. The primary purpose of this gem is to work with public keys, and contains the minimal amount of functionality with private keys needed for testing.
