### ISSUE TITLE
New release for Ruby 3.0 support

### ISSUE THREAD

**Issue by fuegas** [github/ssh_data#28]
Hi,

Would you be inclined to release a new version of this gem? The development branch supports Ruby 3 for a while now but there has been no new version since 1.1.0 (August of 2019). I'd like to keep using ssh_data without having to use the master branch on Github and pin it to a specific commit.

Looking forward to your reply!

**Comment by vcsjones** [comment]
@fuegas 👋 sorry for the delay in response! I think that is a reasonable thing to ask. Let me talk with some folks on cutting a release to put on Rubygems. I can't promise a turn around time on it but I have a note to get this done.

**Comment by vcsjones** [comment]
Well, that was quicker than expected. 1.2.0 has been pushed to rubygems.org.

**Comment by fuegas** [comment]
Hi @vcsjones, thanks for the swift action and support! 💯
